export const CHATROOMS_CREATE_REQUEST = 'CHATROOMS/CREATE:REQUEST';
export const CHATROOMS_CREATE_SUCCESS = 'CHATROOMS/CREATE:SUCCESS';
export const CHATROOMS_CREATE_FAILURE = 'CHATROOMS/CREATE:FAILURE';
