export const CHATROOMS_CREATE_REQUEST = 'CHATROOMS/CREATE:REQUEST';
export const CHATROOMS_CREATE_SUCCESS = 'CHATROOMS/CREATE:SUCCESS';
export const CHATROOMS_CREATE_FAILURE = 'CHATROOMS/CREATE:FAILURE';

export const CHATROOMS_FETCH_REQUEST = 'CHATROOMS/FETCH:REQUEST';
export const CHATROOMS_FETCH_FAILURE = 'CHATROOMS/FETCH:FAILURE';
export const CHATROOMS_FETCH_SUCCESS = 'CHATROOMS/FETCH:SUCCESS';
